export const connectionStatus = {
    CONNECTING: 'CONNECTING',
    CONNECTED: 'CONNECTED',
    DISCONNECTED: 'DISCONNECTED'
}

export const messageTypes = {
    GET_PING: 'GET_PING',
    GET_STATUS: 'GET_STATUS',
    GET_FETCH_STATUS: 'GET_FETCH_STATUS',
    SET_URL: 'SET_URL',
    STOP_FETCH: 'STOP_FETCH',
    TURN_OFF: "TURN_OFF",
    CART_ITEM: "CART_ITEM",
    TURN_ON: "TURN_ON",
    CART_FALSE: "CART_FALSE",
    FETCH_STATUS_CHANGED: 'FETCH_STATUS_CHANGED',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION'
}

export const socketStatus = {
    FETCH_CHANGE: 'FETCH_CHANGE'
}